<?php

namespace ContainerGk14kP0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4_KUy51Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4.kUy51' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4.kUy51'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'users' => ['privates', '.errored..service_locator.4.kUy51.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.4.kUy51": it references class "App\\Entity\\Users" but no such service exists.'],
        ], [
            'users' => 'App\\Entity\\Users',
        ]);
    }
}
