<?php

namespace ContainerGk14kP0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PVeJZFw.App\Entity\Shipping' shared service.
     *
     * @return \App\Entity\Shipping
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PVeJZFw": it references class "App\\Entity\\Shipping" but no such service exists.');
    }
}
