<?php

namespace ContainerZF7Zigp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PTyxqEPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PTyxqEP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PTyxqEP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cgvRepository' => ['privates', 'App\\Repository\\CgvRepository', 'getCgvRepositoryService', true],
        ], [
            'cgvRepository' => 'App\\Repository\\CgvRepository',
        ]);
    }
}
